<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'LearnDash\\The_Events_Calendar\\Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'LearnDash\\The_Events_Calendar\\StellarWP\\Arrays\\Arr' => $vendorDir . '/stellarwp/arrays/src/Arrays/Arr.php',
    'LearnDash\\The_Events_Calendar\\StellarWP\\Templates\\Config' => $vendorDir . '/stellarwp/templates/src/Templates/Config.php',
    'LearnDash\\The_Events_Calendar\\StellarWP\\Templates\\Part_Cache' => $vendorDir . '/stellarwp/templates/src/Templates/Part_Cache.php',
    'LearnDash\\The_Events_Calendar\\StellarWP\\Templates\\Template' => $vendorDir . '/stellarwp/templates/src/Templates/Template.php',
    'LearnDash\\The_Events_Calendar\\StellarWP\\Templates\\Templates' => $vendorDir . '/stellarwp/templates/src/Templates/Templates.php',
    'LearnDash\\The_Events_Calendar\\StellarWP\\Templates\\Utils\\Conditions' => $vendorDir . '/stellarwp/templates/src/Templates/Utils/Conditions.php',
    'LearnDash\\The_Events_Calendar\\StellarWP\\Templates\\Utils\\Paths' => $vendorDir . '/stellarwp/templates/src/Templates/Utils/Paths.php',
    'LearnDash\\The_Events_Calendar\\StellarWP\\Templates\\Utils\\Strings' => $vendorDir . '/stellarwp/templates/src/Templates/Utils/Strings.php',
);
