<?php

// autoload_static.php @generated by Composer

namespace LearnDash\The_Events_Calendar\Composer\Autoload;

class ComposerStaticInit31971f162d3b2b84a888c2c129c86211
{
    public static $prefixLengthsPsr4 = array (
        'L' =>
        array (
            'LearnDash\\The_Events_Calendar\\StellarWP\\Templates\\' => 50,
            'LearnDash\\The_Events_Calendar\\StellarWP\\Arrays\\' => 47,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'LearnDash\\The_Events_Calendar\\StellarWP\\Templates\\' =>
        array (
            0 => __DIR__ . '/..' . '/stellarwp/templates/src/Templates',
        ),
        'LearnDash\\The_Events_Calendar\\StellarWP\\Arrays\\' =>
        array (
            0 => __DIR__ . '/..' . '/stellarwp/arrays/src/Arrays',
        ),
    );

    public static $classMap = array (
        'LearnDash\\The_Events_Calendar\\Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'LearnDash\\The_Events_Calendar\\StellarWP\\Arrays\\Arr' => __DIR__ . '/..' . '/stellarwp/arrays/src/Arrays/Arr.php',
        'LearnDash\\The_Events_Calendar\\StellarWP\\Templates\\Config' => __DIR__ . '/..' . '/stellarwp/templates/src/Templates/Config.php',
        'LearnDash\\The_Events_Calendar\\StellarWP\\Templates\\Part_Cache' => __DIR__ . '/..' . '/stellarwp/templates/src/Templates/Part_Cache.php',
        'LearnDash\\The_Events_Calendar\\StellarWP\\Templates\\Template' => __DIR__ . '/..' . '/stellarwp/templates/src/Templates/Template.php',
        'LearnDash\\The_Events_Calendar\\StellarWP\\Templates\\Templates' => __DIR__ . '/..' . '/stellarwp/templates/src/Templates/Templates.php',
        'LearnDash\\The_Events_Calendar\\StellarWP\\Templates\\Utils\\Conditions' => __DIR__ . '/..' . '/stellarwp/templates/src/Templates/Utils/Conditions.php',
        'LearnDash\\The_Events_Calendar\\StellarWP\\Templates\\Utils\\Paths' => __DIR__ . '/..' . '/stellarwp/templates/src/Templates/Utils/Paths.php',
        'LearnDash\\The_Events_Calendar\\StellarWP\\Templates\\Utils\\Strings' => __DIR__ . '/..' . '/stellarwp/templates/src/Templates/Utils/Strings.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit31971f162d3b2b84a888c2c129c86211::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit31971f162d3b2b84a888c2c129c86211::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit31971f162d3b2b84a888c2c129c86211::$classMap;

        }, null, ClassLoader::class);
    }
}
