<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInit31971f162d3b2b84a888c2c129c86211
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('LearnDash\The_Events_Calendar\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \LearnDash\The_Events_Calendar\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInit31971f162d3b2b84a888c2c129c86211', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \LearnDash\The_Events_Calendar\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInit31971f162d3b2b84a888c2c129c86211', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\LearnDash\The_Events_Calendar\Composer\Autoload\ComposerStaticInit31971f162d3b2b84a888c2c129c86211::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        return $loader;
    }
}
