<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'LearnDash\\Reports\\ZipStream\\' => array($vendorDir . '/maennchen/zipstream-php/src'),
    'LearnDash\\Reports\\Symfony\\Polyfill\\Mbstring\\' => array($vendorDir . '/symfony/polyfill-mbstring'),
    'LearnDash\\Reports\\Psr\\SimpleCache\\' => array($vendorDir . '/psr/simple-cache/src'),
    'LearnDash\\Reports\\Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-factory/src', $vendorDir . '/psr/http-message/src'),
    'LearnDash\\Reports\\Psr\\Http\\Client\\' => array($vendorDir . '/psr/http-client/src'),
    'LearnDash\\Reports\\PhpOffice\\PhpSpreadsheet\\' => array($vendorDir . '/phpoffice/phpspreadsheet/src/PhpSpreadsheet'),
    'LearnDash\\Reports\\MyCLabs\\Enum\\' => array($vendorDir . '/myclabs/php-enum/src'),
    'LearnDash\\Reports\\Matrix\\' => array($vendorDir . '/markbaker/matrix/classes/src'),
    'LearnDash\\Reports\\Composer\\Pcre\\' => array($vendorDir . '/composer/pcre/src'),
    'LearnDash\\Reports\\Complex\\' => array($vendorDir . '/markbaker/complex/classes/src'),
);
