<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInite22265e13e06c5b278f211ab824f8218
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('LearnDash\Reports\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \LearnDash\Reports\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInite22265e13e06c5b278f211ab824f8218', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \LearnDash\Reports\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInite22265e13e06c5b278f211ab824f8218', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\LearnDash\Reports\Composer\Autoload\ComposerStaticInite22265e13e06c5b278f211ab824f8218::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        $filesToLoad = \LearnDash\Reports\Composer\Autoload\ComposerStaticInite22265e13e06c5b278f211ab824f8218::$files;
        $requireFile = \Closure::bind(static function ($fileIdentifier, $file) {
            if (empty($GLOBALS['__composer_autoload_files'][$fileIdentifier])) {
                $GLOBALS['__composer_autoload_files'][$fileIdentifier] = true;

                require $file;
            }
        }, null, null);
        foreach ($filesToLoad as $fileIdentifier => $file) {
            $requireFile($fileIdentifier, $file);
        }

        return $loader;
    }
}
