<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    '778e644a4b81cb7bcfc5bdc6ed2e6029' => $vendorDir . '/symfony/polyfill-mbstring/bootstrap.php',
    '4eebe0263b564783d1c64356e7a56d94' => $vendorDir . '/ezyang/htmlpurifier/library/HTMLPurifier.composer.php',
);
